== Configuring Springfox

:releaseVersion: {springfox-released-version}
:snapshotVersion: {springfox-current-version}

To enable support for swagger specification 1.2 use the ```@EnableSwagger``` annotation

To enable support for swagger specification 2.0 use the ```@EnableSwagger2``` annotation

To document the service we use a ```Docket```. This is changed to be more inline with the fact that expressing the
contents of the documentation is agnostic of the format the documentation is rendered.

Docket https://www.wordnik.com/words/docket[stands for] *A summary or other brief statement of the contents of a
document; an abstract.*

`Docket` helps configure a  subset of the services to be documented and groups them by name. Significant changes
to this is the ability to provide an expressive predicate based for api selection.

.Example configuration
[source,java,linenums]
----
  import static springfox.documentation.builders.PathSelectors.*;
  import static com.google.common.base.Predicates.*;

  @Bean
  public Docket swaggerSpringMvcPlugin() {
    return new Docket(DocumentationType.SWAGGER_2)
            .groupName("business-api")
            .select()
               //Ignores controllers annotated with @CustomIgnore
              .apis(not(withClassAnnotation(CustomIgnore.class)) //Selection by RequestHandler
              .paths(paths()) // and by paths
              .build()
            .apiInfo(apiInfo())
            .securitySchemes(securitySchemes())
            .securityContext(securityContext());
  }

  //Here is an example where we select any api that matches one of these paths
  private Predicate<String> paths() {
    return or(
        regex("/business.*"),
        regex("/some.*"),
        regex("/contacts.*"),
        regex("/pet.*"),
        regex("/springsRestController.*"),
        regex("/test.*"));
  }
----

For a list of handy predicates Look at https://github.com/springfox/springfox/blob/master/springfox-core/src/main/java/springfox/documentation/builders/RequestHandlerSelectors.java[RequestHandlerSelectors]
and https://github.com/springfox/springfox/blob/master/springfox-core/src/main/java/springfox/documentation/builders/PathSelectors.java[PathSelectors].

=== Configuring the ObjectMapper

A simple way to configure the object mapper is to listen for the ```ObjectMapperConfigured``` event. Regardless of
whether there is a customized ObjectMapper in play with a corresponding MappingJackson2HttpMessageConverter, the
library always has a configured ObjectMapper that is customized to serialize swagger 1.2 and swagger 2.0 types.

In order to do this implement the ```ApplicationListener<ObjectMapperConfigured>``` interface. The event has a handle
 to the ObjectMapper that was configured. Configuring application specific ObjectMapper customizations in this
 application event handler guarantees that application specific  customizations will be applied to each and every
 ObjectMapper that is in play.

If you encounter a NullPointerException during application startup like https://github.com/springfox/springfox/issues/635[this issue]. Its because most likely the ```WebMvcConfigurerAdapter``` isn't working.
These adapter especially in a non-spring-boot scenarios will only get loaded if the @EnableWebMvc
http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/servlet/config/annotation/WebMvcConfigurer.html[annotation is present].

If using Spring Boot Web MVC, there is no need to use the @EnableWebMvc annotation, as the framework automatically detects Web MVC usage and configures itself as appropriate.
In this scenario, Springfox will not correctly generate and expose the Swagger UI endpoint (`/swagger-ui.html`) if @EnableWebMvc is present in the application.

Caveat to using the library is that it depends on Jackson for serialization, more importantly the `ObjectMapper`. A
good example of where this breaks down is the following http://stackoverflow.com/a/30220562/19219[issue when using Gson serialization]

=== Customizing the swagger endpoints.

By default the swagger service descriptions are generated at the following urls

.api docs default paths
[options="header,footer"]
|=======================
|Swagger version  | Documentation Url           | Group
|1.2              | /api-docs                   | implicit *default* group
|1.2              | /api-docs?group=external    | *external* group via docket.groupName()
|2.0              | /v2/api-docs                | implicit *default* group
|2.0              | /v2/api-docs?group=external | *external* group via docket.groupName()
|=======================

To customize these endpoints, loading a http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/context/annotation/PropertySource.html[property source] with the following properties
allows the properties to be  overridden

.api docs path properties
[options="header,footer"]
|=======================
|Swagger version | Override property
|1.2             | springfox.documentation.swagger.v1.path
|2.0             | springfox.documentation.swagger.v2.path
|=======================

=== Configuring startup.
If you'd like to delay the startup of springfox, you could choose to set auto-startup to false. The property to use
is `springfox.documentation.auto-startup` and this could either be passed in as a `-D` jvm arg or via a property in
`application.yml/properties` file.

.startup properties
[options="header,footer"]
|=======================
|Override property | description
| true | This is the default value, which starts scanning for endpoints automatically when
the spring contexts is refreshed.
| false | This setting starts scanning for endpoints only when when the `Lifecycle#start()` method is called explicitly.
This is very useful for frameworks like grails that has its own lifecycle. It indicates that the library
user is responsible for starting the `DocumentationPluginsBootStrapper` lifecycle.
|=======================

WARNING: Change this default to `false` with caution. This implies managing the startup of the plugins prior to
requesting the swagger endpoints in a thread-safe manner.

=== Overriding descriptions via properties
Added support for resolving properties in property sources to replace expressions in certain annotations. In order to
 use it simply define properties in `application.properties`, `application.yml` file or property files in your
 classpath with values that you'd like to see replaced in known annotations. For e.g. `@ApiModelProperty(value="${property1.description}")`
 will evaluate `property1.description` from the available properties. If none is found, it will render the
 un-resolved expression as-is.

Currently supported list of annotations are in order of priority within the annotation:

.description resolution targets
[options="header,footer"]
|===
|Annotation | Attribute | Target Property | Description

| ApiModelProperty
| value
| ModelProperty#description
| e.g. `@ApiModelProperty(value="${property1.description}")`

| ApiModelProperty
| description
| ModelProperty#description
| e.g. `@ApiModelProperty(notes="${property1.description}")`

| ApiParam
| value
| Parameter#description
| e.g. `@ApiParam(value="${param1.description}")`

| ApiImplicitParam
| value
| Parameter#description
| e.g. `@ApiImplicitParam(value="${param1.description}")`

| ApiOperation
| notes
| Operation#notes
| e.g. `@ApiOperation(notes="${operation1.description}")`

| ApiOperation
| summary
| Operation#summary
| e.g. `@ApiOperation(value="${operation1.summary}")`

| RequestParam
| defaultValue
| Parameter#defaultValue
| e.g. `@RequestParam(defaultValue="${param1.defaultValue}")`

| RequestHeader
| defaultValue
| Parameter#defaultValue
| e.g. `@RequestHeader(defaultValue="${param1.defaultValue}")`
|===

For a detailed explanation <<property-file-lookup, see here>>.

=== Overriding property datatypes

Using the `ApiModelProperty#dataType` we can override the inferred data types. However it is restricted
 to only allow data types to be specified with a fully qualified class name. For e.g. if we have the following
 definition

.Example data type override
[source,java,linenums]
----

// if com.qualified.ReplaceWith is not a Class that can be created using Class.forName(...)
// Original will be replaced with the new class
@ApiModelProperty(dataType = "com.qualified.ReplacedWith")
public Original getOriginal() { ... }

// if ReplaceWith is not a Class that can be created using Class.forName(...) Original will be preserved
@ApiModelProperty(dataType = "ReplaceWith")
public Original getAnotherOriginal() { ... }

----

NOTE: In the case of `ApiImplicitParam#dataType`, since the type itself is usually a scalar type (string, int)
use one of the base types specified in the Types class =>
`springfox-schema/src/main/java/springfox/documentation/schema/Types.java`

.Primitive types
[source,groovy,linenums]
----
include::../../springfox-schema/src/main/java/springfox/documentation/schema/Types.java[lines=42..56]
----


=== Docket XML Configuration

To use the plugin you must create a spring java configuration class which uses spring's `@Configuration`.
This config class must then be defined in your xml application context.


.Xml Configuration
[source,xml,linenums]
----
<!-- Required so springfox can access spring's RequestMappingHandlerMapping  -->
<mvc:annotation-driven/>

<!-- Required to enable Spring post processing on @Configuration classes. -->
<context:annotation-config/>

<bean class="com.yourapp.configuration.MySwaggerConfig"/>
----

.Configuration bean pulled into xml a configuration as a bean
[source,java,linenums]
----

@Configuration
@EnableSwagger //Loads the spring beans required by the framework
public class MySwaggerConfig {

   /**
    * Every Docket bean is picked up by the swagger-mvc framework - allowing for multiple
    * swagger groups i.e. same code base multiple swagger resource listings.
    */
   @Bean
   public Docket customDocket(){
      return new Docket(); //some customization goes here
   }

}
----


=== Docket Spring Java Configuration

- Use the `@EnableSwagger` or `@EnableSwagger2` annotation.
- Define one or more Docket instances using springs `@Bean` annotation.

.Java Configuration
[source,java,linenums]
----
@Configuration
@EnableWebMvc //NOTE: Only needed in a non-springboot application
@EnableSwagger2
@ComponentScan("com.myapp.controllers")
public class CustomJavaPluginConfig {


   @Bean //Don't forget the @Bean annotation
   public Docket customImplementation(){
      return new Docket()
            .apiInfo(apiInfo());
            //... more options available

   }

   //...
}
----

[[property-file-lookup]]
=== Support for documentation from property file lookup

Starting with `2.7.0` we support looking up description from the following annotations given a property just like
property place holders resolve a value annotation `@Value(${key})`. The following annotations attributes support
description resolution.

- `@ApiParam#value()`
- `@ApiImplicitParam#value()`
- `@ApiModelProperty#value()`
- `@ApiOperation#value()`
- `@ApiOperation#notes()`
- `@RequestParam#defaultValue()`
- `@RequestHeader#defaultValue()`

Below are examples of how it would work

[[controller-description]]Controller Example
[source,java]
.SomeController.java
----

  @ApiOperation(value = "Find pet by Status",
      notes = "${SomeController.findPetsByStatus.notes}"...) //<1>
  @RequestMapping(value = "/findByStatus", method = RequestMethod.GET, params = {"status"})
  public Pet findPetsByStatus(
      @ApiParam(value = "${SomeController.findPetsByStatus.status}", //<2>
           required = true,...)
      @RequestParam("status",
          defaultValue="${SomeController.findPetsByStatus.status.default}") String status) { //<3>
      //...
  }

  @ApiOperation(notes = "Operation 2", value = "${SomeController.operation2.value}"...) //<4>
  @ApiImplicitParams(
      @ApiImplicitParam(name="header1", value="${SomeController.operation2.header1}", ...) //<5>
  )
  @RequestMapping(value = "operation2", method = RequestMethod.POST)
  public ResponseEntity<String> operation2() {
    return ResponseEntity.ok("");
  }
----

<1> Example of `@ApiOperation#notes()`
<2> Example of `@ApiParam#value()`
<3> Example of `@RequestParam#defaultValue()`
<4> Example of `@ApiOperation#value()`
<5> Example of `@ApiImplicitParams#value()`

[[model-description]]Model Example
[source,java]
.SomeModel.java
----
  public class SomeModel {
    @ApiModelProperty(value = "${SomeModel.someProperty}", ...) //<1>
    private long someProperty;
  }
----

<1> Example of `@ApiModelProperty#value()`

To provide these properties via external properties just add it to your application property file or any property
source configured by the application as shown below. When a property place holder cannot be found the default
behavior is to echo the expression as-is.

[source,properties]
.application.properties
----
SomeController.findPetsByStatus.notes=Finds pets by status
SomeController.findPetsByStatus.status=Status could be one of ...
SomeController.operation2.header1=Header for bla bla...
SomeController.operation2.value=Operation 2 do something...
SomeModel.someProperty=Some property description
----

==== Swagger group

A swagger group is a concept introduced by this library which is simply a unique identifier for a Swagger Resource Listing
within your application. The reason this concept was introduced was to support applications which require more than one
Resource Listing. Why would you need more than one Resource Listing?
- A single Spring Web MVC  application serves more than one API e.g. publicly facing and internally facing.
- A single Spring Web MVC  application serves multiple versions of the same API. e.g. v1 and v2

In most cases an application will not need more than one Resource Listing and the concept of swagger groups can be ignored.

==== Configuring the output of _operationId_ in a Swagger 2.0 spec

As defined https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#fixed-fields-5[`operationId` was
introduced] in the Swagger 2.0 spec, the `operationId` parameter, which was referred to as `nickname` in pre-2.0
versions of the Swagger spec, provides the author a means by which to describe an API operation with a friendly name
. This field is often used by consumers of a Swagger 2.0 spec in order to name functions in generated clients. An
example of this can be seen in the https://github.com/swagger-api/swagger-codegen[swagger-codegen project].

===== The default value of `operationId` according to Springfox

By default, when using Springfox in Swagger 2.0 mode, the value of `operationID` will be rendered using the
following structure: "`[java_method_name_here]Using[HTTP_verb_here]`". For example, if one has a method `getPets()`
connected to an HTTP GET verb, Springfox will render `getPetsUsingGET` for the operationId.

====== Given this annotated method ...

.Standard Annotation On Method
[source,java,linenums]
----
@ApiOperation(value = "")
@RequestMapping(value = "/pets", method = RequestMethod.GET)
public Model getAllThePets() {
    ...
}
----

====== the default `operationId` will render looking like this:

.Default Rendered Operation Id
[source,json,linenums]
----

"paths": {
  "/pets": {
    "get": {
            ...
      "operationId":"getAllThePetsUsingGET"
      ...
    }
  }
}

----

===== Customizing the value of _operationId_

In the event you wish to override the default `operationId` which Springfox renders, you may do so by providing the
`nickname` element in an `@ApiOperation` annotation.

====== Given this annotated method ...

.Nickname overrides default operationId
[source,java,linenums]
----
@ApiOperation(value = "", nickname = "getMeAllThePetsPlease")
@RequestMapping(value = "/pets", method = RequestMethod.GET)
public Model getAllThePets() {
    ...
}
----

====== ... the customized *operationId* will render looking like this:

.Default Rendered Operation Id
[source,json,linenums]
----

"paths": {
  "/pets": {
    "get": {
            ...
      "operationId":"getMeAllThePetsPlease"
      ...
    }
  }
}
----

==== Changing how Generic Types are Named

By default, types with generics will be labeled with '\u00ab'(<<), '\u00bb'(>>), and commas. This can be problematic
with things like swagger-codegen. You can override this behavior by implementing your own `GenericTypeNamingStrategy`.
For example, if you wanted `List<String>` to be encoded as 'ListOfString' and `Map<String, Object>`
to be encoded as 'MapOfStringAndObject' you could set the `forCodeGeneration` customization option to `true` during
plugin customization:

[source,json,linenums]
----
 docket.forCodeGeneration(true|false);
----

=== Caching

The caching feature that was introduced in 2.1.0 has been removed. Springfox no longer uses the cache abstraction to
improve performance the api scanners and readers. It has been rolled into the library as an internal implementation
detail as of 2.1.2. This is a runtime breaking change, however, since its not really breaking api compatibility change
other than the introduction of configuration change in consuming applications, we're not incrementing the minor version.

=== Configuring Security Schemes and Contexts an Overview

The security provisions in SpringFox at a high level, without getting into the code, has different pieces
that all work together in concert

- The API itself needs to be protected. This is achieved by using, for simplicity sake, spring security and may also
use a combination of servlet container and tomcat/jersey etc.
- The security scheme which describes the techniques you've used to protect the api. Spring fox supports whatever
schemes swagger specification supports (ApiKey, BasicAuth and OAuth2 (certain profiles))
- Finally the security contexts which actually provides information on which api's are protected by which schemes. I
think in your example, you're missing the last piece of the puzzle, the security context see  xref:getting-started-spring-boot[15].

=== Example application

For an examples for spring-boot, vanilla spring applications take a look https://github.com/springfox/springfox-demos[examples]
in the demo application.

== Configuring springfox-staticdocs

IMPORTANT: Support for this module has been deprecated in 2.7.0. Since swagger2markup doesnt support jdk6 anymore it is
difficult for build to co-exist with the newer version of swagger2markup. Please use the
_latest_ instructions provided in the awesome https://github.com/Swagger2Markup/swagger2markup[Swagger2Markup Library].

== Security

Thanks to https://github.com/mojaiq[Javed Mohammed] we now have an example https://github.com/springfox/springfox-oath2-demo[oauth demo].

NOTE: this is based on swagger-ui pre 3.x

