== Plugins
=== Introduction
Any plugin or extensibility hook that is available https://github.com/springfox/springfox/tree/master/springfox-spi/src/main/java/springfox/documentation/spi[is available in the SPI
module]. In the `spi` module, anything that ends in `*Plugin` is generally an extensibility point that is meant for
library consumers to consume.

The bean validation (JSR-303) is a great example of a contribution to https://github.com/springfox/springfox/tree/master/springfox-bean-validators[support bean validations]. Its fairly simple and small in scope and should
give an idea how one goes about creating a plugin. Its a set of plugins are act on `ModelProperty`, hence they
are  implementations of `ModelPropertyBuilderPlugin`.

=== Plugins Available For Extensibility
To explicitly state the extensibility points that are available:
* At the schema level
.Schema Plugins
|===
|Name| Description

| `ModelBuilderPlugin`
| for enriching models

| `ModelPropertyBuilderPlugin`
| for enriching model properties

| `TypeNameProviderPlugin`
| these are for overriding names for models
|===


.Service Plugins
|===
|Name| Description

| `ApiListingScannerPlugin`
| for adding custom api descriptions (see <<index.adoc#_example_apilistingscannerplugin,example>>).

| `ApiListingBuilderPlugin`
| for enriching api listings

| `DefaultsProviderPlugin`
| for providing your own defaults

| `DocumentationPlugin`
| for enriching the documentation context

| `ExpandedParameterBuilderPlugin`
| for parameter expansion used in the context of `@ModelAttribute`

| `OperationBuilderPlugin`
| for enriching operations

| `OperationModelsProviderPlugin`
| for providing additional models that you might load a different way

| `ParameterBuilderPlugin`
| for enriching parameters (see <<index.adoc#_example_parameterbuilderplugin,example>>)
|===

.Swagger 2.0 specific plugins
|===
|Name| Description

| `WebMvcSwaggerTransformationFilter`
| Specifically used with a servlet application, it is useful for transforming the generated open api.
Out of the box it comes with one plugin that sets the host name and base path. Typically, this the most common
thing to use this plugin for. Having said that this plugin has the power to rewrite the whole specification if required.

| `WebFluxSwaggerTransformationFilter`
| Specifically used with a web flux application, it is useful for transforming the generated open api.
Out of the box it comes with one plugin that sets the host name and base path. Typically, this the most common
thing too use this plugin for. Having said that this plugin has the power to rewrite the whole specification if required.
|===

.Open API 3.0 specific plugins
|===
|Name| Description

| `WebMvcOpenApiTransformationFilter`
| Specifically used with a servlet application, it is useful for transforming the generated open api.
Out of the box it comes with one plugin that sets the host name and base path. Typically, this the most common
thing to use this plugin for. Having said that this plugin has the power to rewrite the whole specification if required.

| `WebFluxOpenApiTransformationFilter`
| Specifically used with a web flux application, it is useful for transforming the generated open api.
Out of the box it comes with one plugin that sets the host name and base path. Typically, this the most common
thing to use this plugin for. Having said that this plugin has the power to rewrite the whole specification if required.
|===


=== Steps To Create A Plugin

TIP: The ___same___ patterns apply to all of the extensibility mechanisms

1. Implement one of the above plugin interfaces
2. Give the plugin an order for e.g. https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/readers/parameter/ApiParamParameterBuilder.java#L42[ApiParamParameterBuilder] has an
 order specified in the bean. In general spring plugins get the highest priority, The swagger plugins (the ones that process all the `@Api...` annotations) layer information on top. So the order that you'd write will need to layer information at the end.
3. Each plugin has
     - a https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/readers/parameter/ApiParamParameterBuilder.java#L47[*context] and provides access to any information that the plugin might need to do its job
     - a https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/readers/parameter/ApiParamParameterBuilder.java#L49[*builder] for the type of object that the plugin is intended to support for e.g. a `ModelPropertyBuilderPlugin` will have access to a `ModelPropertyBuilder`. This builder is what is used to build the model _after_ all the plugins have had access to contribute/enrich the underlying object.
4. Update any builder properties your plugin cares about
5. Register the plugin as a `@bean`, so that the plugin registry can pick it up.

That is it!

==== Example OperationBuilderPlugin

This example by https://github.com/koderman[@koderman]  is a custom extension for https://aws.amazon.com/api-gateway/[AWS Amazon Api Gateway] integration.

++++
<script src="https://gist.github.com/koderman/d49a67274e33f03405a8e45672794968.js"></script>
++++

==== Example ParameterBuilderPlugin

Here is an example of how to add parameters by hand.

Consider this controller, https://github.com/springfox/springfox/blob/master/springfox-spring-config/src/main/java/springfox/springconfig/VersionedController.java[VersionedController.java]
[[version-annotated-controller-example]]
[source,java,linenums]
----
include::../../springfox-spring-config/src/main/java/springfox/springconfig/VersionedController.java[tags=version-annotated-controller,indent=0]
----
<1> Parameter annotated with https://github.com/springfox/springfox/blob/master/springfox-spring-config/src/main/java/springfox/springconfig/VersionApi.java[`@VersionApi`]

We then create a plugin https://github.com/springfox/springfox/blob/master/springfox-spring-config/src/main/java/springfox/springconfig/VersionApiReader.java[VersionApiReader.java] to provide custom parameter information.
[[parameter-building-plugin-example]]
[source,java,linenums]
----
include::../../springfox-spring-config/src/main/java/springfox/springconfig/VersionApiReader.java[tags=parameter-builder-plugin,indent=0]
----
<1> Specify an order for the plugin to execute. Higher the number, later the plugin is applied.
<2> Check if the https://github.com/springfox/springfox/blob/master/springfox-spring-config/src/main/java/springfox/springconfig/VersionApi.java[VersionApi]
is applied to the parameter.
<3> Build the parameter with the necessary information using the builder methods.
<4> Return true if we want this plugin to apply to all documentation types.

==== Example ApiListingScannerPlugin

Here is an example of how to add Api Descriptions by hand.

https://github.com/springfox/springfox/blob/master/swagger-contract-tests/src/main/java/springfox/test/contract/swagger/Bug1767ListingScanner.java[Bug1767ListingScanner.java]
[[api-listing-plugin-example]]
[source,java,linenums]
----
include::../../swagger-contract-tests/src/main/java/springfox/test/contract/swagger/Bug1767ListingScanner.java[tags=api-listing-plugin,indent=0]
----
<1> Add a list of custom ``ApiDescription``s
<2> Add a list of ``Operation``s for each description
<3> NOTE: the code generated names are not guaranteed to be unique. For these custom endpoints it is the
responsibility of the service author to ensure.
<4> Added parameters to the operation
<5> NOTE: It is important to also ensure we pass in a model reference even for primitive types
<6> Set of response messages that overide the default/global response messages
<7> Response model reference of the default model returned by the operation. Usually the  response model returned
in a 200 or 201 response.
<8> Optionally provide a group name, if provided this api  will only appear under that group. If absent,
the api will appear under the default group.
<9> CachingOperationNameGenerator is a component bean that is available to be autowired

== Additional extensibility options
.Other Extensibility
|====
|Name| Description | Since

| `RequestHandlerCombiner`^1^
| for combining apis that react to the same API endpoint given the same input criteria but produces different output.
 We provide a `DefaultRequestHandlerCombiner` but this is an extensibility point added to customize it.
| 2.7.0
| `AlternateTypeRuleConvention`
| To provide a convention based type rules. Ideally we use these when its cumbersome to define individual types either
because there are just too many, or even in some cases where it involves creating mixin types just for the sake of
OpenAPI documentation. https://github.com/springfox/springfox/blob/ef1721afc4c910675d9032bee59aea8e75e06d27/springfox-spring-web/src/main/java/springfox/documentation/spring/web/plugins/JacksonSerializerConvention.java[`JacksonSerializerConvention`]
 is an example of how we apply rules to types annotated with `JsonSerialize`/`JsonDeserialize`.  
| 2.7.0
| `SwaggerResourcesProvider`
| Extensibility which allows overriding how the swagger resources are served. By default we serve APIs hosted on the
same application. This can be used to aggregate APIs as well.
| 2.7.0
|====

NOTE: 1. This has a shortcoming currently in that, currently the response still hides one of the response
representations. This is a limitation of the OAI Spec 2.0.

=== Examples of alternate type rule convention
==== JacksonSerializerConvention

Here is how we configure the `JacksonSerializerConvention`.

https://github.com/springfox/springfox/blob/c48a8bb019371cb1e3c79d24c3db3791ac5025cc/swagger-contract-tests/src/test/groovy/springfox/test/contract/swaggertests/FunctionContractSpec.groovy#L201-L204[FunctionContractSpec.java]
[[jackson-convention-example-1]]
[source,java,linenums]
----
include::../../swagger-contract-tests/src/test/groovy/springfox/test/contract/swaggertests/FunctionContractSpec.groovy[tags=alternate-type-rule-convention,indent=0]
----

==== Creating a convention

Below is an example for creating a rule that automatically provides a convention for configuring `Pageable` type.

https://github.com/springfox/springfox/blob/ef1721afc4c910675d9032bee59aea8e75e06d27/springfox-data-rest/src/main/java/springfox/documentation/spring/data/rest/configuration/SpringDataRestConfiguration.java#L46-L64[SpringDataRestConfiguration.java]
[[jackson-convention-example-2]]
[source,java,linenums]
----
include::../../springfox-data-rest/src/main/java/springfox/documentation/spring/data/rest/configuration/SpringDataRestConfiguration.java[tags=alternate-type-rule-convention,indent=0]
----

It involves creating a generated in-memory type that allows the springfox inference engine to use the new type
instead of `Pageable`.

https://github.com/springfox/springfox/blob/ef1721afc4c910675d9032bee59aea8e75e06d27/springfox-data-rest/src/main/java/springfox/documentation/spring/data/rest/configuration/SpringDataRestConfiguration.java#L68-L88[SpringDataRestConfiguration.java]
[[in-memory-alternate-type]]
[source,java,linenums]
----
include::../../springfox-data-rest/src/main/java/springfox/documentation/spring/data/rest/configuration/SpringDataRestConfiguration.java[tags=alternate-type-builder,indent=0]
----

=== Aggregating multiple swagger specifications in the same swagger-ui

You need to create a bean that implements the https://github.com/springfox/springfox/blob/cef36c0b0a3e20ef2cb0c23a76ee34866abaf490/springfox-swagger-common/src/main/java/springfox/documentation/swagger/web/SwaggerResourcesProvider.java#L25-L26[`SwaggerResourcesProvider`]
interface. Typically you'd have to make a composite bean that uses multiple https://github.com/springfox/springfox/blob/cef36c0b0a3e20ef2cb0c23a76ee34866abaf490/springfox-swagger-common/src/main/java/springfox/documentation/swagger/web/InMemorySwaggerResourcesProvider.java#L38[InMemorySwaggerResourcesProvider]
and adds your own json file to it as well.

NOTE: You need to make this new bean a @Primary bean. otherwise the you'd get an exception about ambiguous beans.

[[multiple-swagger-aggregate]]
[source,java,linenums]
----
@Configuration
public class SwaggerWsEndpointsConfig {

    @Primary
    @Bean
    public SwaggerResourcesProvider swaggerResourcesProvider(InMemorySwaggerResourcesProvider defaultResourcesProvider) {
        return () -> {
            SwaggerResource wsResource = new SwaggerResource();
            wsResource.setName("ws endpoints");
            wsResource.setSwaggerVersion("2.0");
            wsResource.setLocation("/v2/websockets.json");

            List<SwaggerResource> resources = new ArrayList<>(defaultResourcesProvider.get());
            resources.add(wsResource);
            return resources;
        };
    }
}
----

== Spring Data Rest extensibility

NOTE: These are incubating features and may change.

.Spring Data REST Extensibility
|====
|Name| Description | Since
| `EntityOperationsExtractor`
| This is an extensibility point to extract entity specific operations. This extractor is to allow creation of
`RequestHandler`s that are based on Spring-Data-Rest(SDR) endpoints. The SDR configuration information is available
via `EntityAssociationContext` and can be used to infer the properties needed
to produce the operation descriptions.
| 2.7.0
| `EntityAssociationOperationsExtractor`
| This is an extensibility point to extract operations related to entity associations. This extractor is to allow
creation of `RequestHandler`s that are based on Spring-Data-Rest(SDR). The SDR configuration information is available
via `EntityContext` and can be used to infer the properties needed to produce the operation descriptions.
| 2.7.0
| `RequestHandlerExtractorConfiguration`
| Additionally the glue that makes all this possible is the `RequestHandlerExtractorConfiguration`. When not
customized, the library uses the `DefaultExtractorConfiguration`.
| 2.7.0
|====