== Swagger

Springfox supports both version https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md[1.2] and version
https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md[2.0] of the http://swagger.io/[Swagger] specification.
Where possible, the Swagger 1.2 specification is preferable.

The https://github.com/swagger-api/swagger-core/wiki/Annotations[Swagger-Core Annotations], as provided by
https://github.com/swagger-api/swagger-core[swagger-core], are typically used to decorate the java source code of an API which is bing
'swaggered'. Springfox is aware of the Swagger-Core Annotations and will favor those annotations over inferred defaults.

=== Swagger 1.2 vs Swagger 2.0
One major difference between the two swagger specification is the composition of the generated swagger documentation.

With Swagger 1.2 an applications API is represented as a `Resource Listing` and multiple `API Declarations` which has the
implication of producing https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2
.md#42-file-structure[multiple JSON files]

With Swagger 2.0 things are much simpler and an Application's API can be represented in a single JSON file.

=== Springfox Spring Web Configuration
The following secton describes how to configure Springfox with Swagger for Spring Web MVC based applications.

The https://github.com/springfox/springfox-demos[springfox-demos] repository contains a number of sample Spring application
which can be used a reference.


==== Spring XML Configuration

==== Spring Java Configuration (javaconfig)

==== Spring Boot

=== Swagger Specification version 2.0

=== Swagger UI